name: docker

on:
  workflow_call:
  

jobs:

  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: ['', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v4

    - name: Set up docker build
      uses: docker/setup-buildx-action@v3.5.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: apigo
    
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: wessnervini
        password: ${{ secrets.DOCKER_HUB_LOGIN }}         

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.5.0
      with:
          context: .
          file: ./dockerfile
          push: true
          tags: wessnervini/cursoci:${{github.ref_name}}

