name: Testando minha aplicacao

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Teste:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_versions: ['1.18', '1.17', '>=1.18']
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{matrix.go_versions}}

    - name: build banco de dados
      run: docker-compose build

    - name: criando banco de dados
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go


  Build:
    needs: Teste
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: go build -v main.go
